"""Export local immutable runtime assets and their auditable byte/hash manifest.
No network, training, or publish side effects. Safe to rerun after model evaluation.
"""
import argparse,hashlib,json,os,re
from pathlib import Path
from sim import ROOT
from contract import JUDGE_VERSION, runtime_contract, validate_contract

def export(policy,initial,status,cross_physics_baseline=False,qualification=None):
 if status=='release' and qualification is None:raise ValueError('A release export requires the frozen native/WASM qualification directory.')
 public=ROOT/'public';sources={'xml':ROOT/'public/physics/diver.xml','policy':Path(policy),'initial':Path(initial)}
 # Read each source once. A concurrent atomic checkpoint export cannot mix a
 # model's coefficients, training counters and contract from different versions.
 payloads={key:path.read_bytes()for key,path in sources.items()}
 expected=runtime_contract();models={}
 for key in ['policy','initial']:
  models[key]=json.loads(payloads[key])
  try:validate_contract(models[key].get('contract'),expected)
  except ValueError:
   if not cross_physics_baseline or status!='development':raise
   models[key]['crossPhysicsBaseline']=True
 if models['initial']['steps']!=0:raise ValueError('The zero-experience comparison must have zero training decisions.')
 if status=='release' and models['policy']['contract'].get('stepsOnContract',0)<=0:raise ValueError('A release must have training decisions on the current physical contract.')
 assets={};files=[]
 for key,source in sources.items():
  payload=payloads[key]
  if key!='xml':
   model=models[key]
   for layer in model['layers']:
    layer['weight']=[[round(float(x),8) for x in row] for row in layer['weight']]
    layer['bias']=[round(float(x),8) for x in layer['bias']]
   payload=json.dumps(model,separators=(',',':')).encode()
  sha=hashlib.sha256(payload).hexdigest();folder='physics'if key=='xml'else'models';name='diver'if key=='xml'else key;ext='xml'if key=='xml'else'json';path=f'{folder}/{name}.{sha[:16]}.{ext}'
  (public/path).parent.mkdir(parents=True,exist_ok=True);(public/path).write_bytes(payload)
  entry={'key':key,'path':path,'sha256':sha,'bytes':len(payload)};assets[key]=entry;files.append(entry)
 manifest={'contract':expected,'policyContract':models['policy'].get('contract'),'initialContract':models['initial'].get('contract'),'crossPhysicsBaseline':bool(cross_physics_baseline),'judge':{'id':JUDGE_VERSION,'sourceSHA256':{name:hashlib.sha256((ROOT/name).read_bytes()).hexdigest() for name in ['training/sim.py','training/water.py','training/evaluate.py','src/core/control.js','src/core/physics.js','src/core/water.js']}},'observationSemantics':expected['observationSemantics'],'schemaVersion':1,'id':'learn-to-dive','status':status,'physics':{'name':'MuJoCo','version':'3.13.0'},'trainingSteps':models['policy']['steps'],'files':files}
 frozen=sources['policy'].parent/'freeze.json'
 if frozen.exists():
  proof=json.loads(frozen.read_bytes());native=sources['policy'].parent/'checkpoint.pt';native_bytes=native.read_bytes()
  if proof['policySHA256']!=assets['policy']['sha256'] or proof['steps']!=models['policy']['steps'] or proof['contract']!=models['policy']['contract']:raise ValueError('Frozen checkpoint proof differs from the exported policy.')
  if hashlib.sha256(native_bytes).hexdigest()!=proof['checkpointSHA256']:raise ValueError('Frozen native checkpoint bytes differ from their provenance.')
  manifest['checkpointProvenance']={'sha256':proof['checkpointSHA256'],'bytes':len(native_bytes),'steps':proof['steps'],'stepsOnContract':proof['contract']['stepsOnContract'],'trainingSourceSHA256':proof['contract']['trainingSourceSHA256'],'description':'Immutable native PPO optimizer checkpoint, with source/config/counter provenance; checkpoint bytes are retained in the source delivery, not the browser package.'}
 if status=='release':
  from qualify import check
  directory=Path(qualification);report=json.loads((directory/'evaluation.json').read_bytes());runtime=json.loads((directory/'runtime-audit.json').read_bytes());protocol=json.loads((ROOT/'training/evaluation-protocol.json').read_bytes())
  errors=check(report,runtime,manifest,protocol)
  if errors:raise ValueError('Release export is not qualified:\n- '+'\n- '.join(errors))
 (public/'asset-manifest.tmp.json').write_text(json.dumps(manifest,indent=2)+'\n')
 os.replace(public/'asset-manifest.tmp.json',public/'asset-manifest.json')
 literals=','.join(f"{key}:new URL('../../public/{entry['path']}',import.meta.url).href"for key,entry in assets.items())
 paths=json.dumps({key:value['path']for key,value in assets.items()},separators=(',',':'))
 source=f'''// Generated by training/export_assets.py. Files are immutable by their content hash.
export const ASSET_PATHS=Object.freeze({paths});
const DEFAULT_URLS=Object.freeze({{{literals}}});
export function assetURLs(base){{if(!base)return DEFAULT_URLS;const root=new URL(base,location.href);return Object.fromEntries(Object.entries(ASSET_PATHS).map(([key,path])=>[key,new URL(path,root).href]));}}
'''
 (ROOT/'src/data/assets.js').write_text(source)
 keep={entry['path']for entry in files}
 for folder in ['models','physics']:
  for old in (public/folder).iterdir():
   if re.fullmatch(r'(policy|initial|diver)\.[0-9a-f]{16}\.(json|xml)',old.name) and old.relative_to(public).as_posix() not in keep:old.unlink()
 print(json.dumps(manifest,indent=2))
if __name__=='__main__':
 p=argparse.ArgumentParser();p.add_argument('--policy',default=str(ROOT/'training/ppo-v2/policy.json'));p.add_argument('--initial',default=str(ROOT/'training/initial-squashed.json'));p.add_argument('--cross-physics-baseline',action='store_true');p.add_argument('--status',choices=['development','release'],default='development');p.add_argument('--qualification');a=p.parse_args();export(a.policy,a.initial,a.status,a.cross_physics_baseline,a.qualification)
